---
new_page_extension: md
auto_deploy: false
admin_path: static/admin
webhook_url: ''
sections:
- type: directory
  path: src/articles
  label: Wiederverwendbare Inhaltselemente
  create: documents
  match: "**/*.md"
  templates:
  - simple-page
- type: directory
  path: src/pages
  label: Ver√∂ffentlichte Seiten
  create: all
  match: "**/*.md"
  new_doc_ext: md
  templates:
  - simple-page
  - complex-page
- type: heading
  label: Einstellungen
- type: document
  path: src/lists/nav.yml
  label: Navigation
- type: directory
  path: src/lists
  label: Listen
  create: documents
  match: "*.*"
  exclude: nav.yml
  new_doc_ext: yml
  templates:
  - list
upload_dir: src/images
public_path: "/media-t51ivd"
front_matter_path: ''
use_front_matter_path: false
file_template: ":year:-:month:/:filename:"
build:
  preview_env:
  - PATH_PREFIX=/
  - GATSBY_WEBPACK_PUBLICPATH=/
  preview_output_directory: public
  install_dependencies_command: npm install
  preview_docker_image: node:14
  mount_path: "/srv/app"
  working_dir: "/srv/app"
  instant_preview_command: npm run forestry:preview
